# Generated by Django 3.2.7 on 2022-01-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120, verbose_name='тема')),
                ('number_of_questions', models.IntegerField(verbose_name='количество вопросов')),
                ('required_score_to_pass', models.IntegerField(help_text='требуемый балл в %')),
                ('difficluty', models.CharField(choices=[('легкий', 'легкий'), ('средний', 'средний'), ('сложные', 'сложные')], max_length=50, verbose_name='трудность')),
            ],
            options={
                'verbose_name': ' Группировать вопросы',
                'verbose_name_plural': 'Группировать вопросы',
            },
        ),
    ]
